---
framework: jasmine
postMerge:
  pattern:
    - "./spec/**/*Spec.js"
blacklist:
  - 'spec/JUnitXmlReporterSpec.js##JUnitXmlReporter##constructor##file prefix##'
preMerge:
  pattern:
    - "./spec/**/*Spec.js"
preRun:
 command:
  - npm i
postRun:
 command:
  - node --version
version: 1.3
  
